//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MGK.ServiceBase.API.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program terminated unexpectedly!.
        /// </summary>
        public static string ErrorApplicationBrake {
            get {
                return ResourceManager.GetString("ErrorApplicationBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request - Invalid Request Exception: {0}.
        /// </summary>
        public static string ErrorBadRequest {
            get {
                return ResourceManager.GetString("ErrorBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path that defines the context of the API is not defined..
        /// </summary>
        public static string ErrorContextPathNotDefined {
            get {
                return ResourceManager.GetString("ErrorContextPathNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service parameters were not registered..
        /// </summary>
        public static string ErrorSwaggerRegistrationDescription {
            get {
                return ResourceManager.GetString("ErrorSwaggerRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger Registration Error.
        /// </summary>
        public static string ErrorSwaggerRegistrationTitle {
            get {
                return ResourceManager.GetString("ErrorSwaggerRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request, reasons:.
        /// </summary>
        public static string ErrorValidatorsTitle {
            get {
                return ResourceManager.GetString("ErrorValidatorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Business Validation.
        /// </summary>
        public static string ErrorWithBusinessValidation {
            get {
                return ResourceManager.GetString("ErrorWithBusinessValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body {RequestBody}.
        /// </summary>
        public static string InfoRequestBody {
            get {
                return ResourceManager.GetString("InfoRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request headers {RequestHeaders}.
        /// </summary>
        public static string InfoRequestHeaders {
            get {
                return ResourceManager.GetString("InfoRequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request information {RequestMethod} {RequestPath}.
        /// </summary>
        public static string InfoRequestMethodPath {
            get {
                return ResourceManager.GetString("InfoRequestMethodPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request query string {QueryString}.
        /// </summary>
        public static string InfoRequestQueryString {
            get {
                return ResourceManager.GetString("InfoRequestQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request started by user: {UserName} from client IP: {ClientIp} with UserAgent: {ClientAgent}.
        /// </summary>
        public static string InfoRequestStart {
            get {
                return ResourceManager.GetString("InfoRequestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response body {ResponseBody}.
        /// </summary>
        public static string InfoResponseBody {
            get {
                return ResourceManager.GetString("InfoResponseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response content type {ContentType}.
        /// </summary>
        public static string InfoResponseContentType {
            get {
                return ResourceManager.GetString("InfoResponseContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response information {RequestMethod} {RequestPath} {statusCode}.
        /// </summary>
        public static string InfoResponseGeneral {
            get {
                return ResourceManager.GetString("InfoResponseGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &apos;Bearer&apos; following by space and the token..
        /// </summary>
        public static string InformationSwaggerDescription {
            get {
                return ResourceManager.GetString("InformationSwaggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string InformationSwaggerName {
            get {
                return ResourceManager.GetString("InformationSwaggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up.
        /// </summary>
        public static string LoggingStartUp {
            get {
                return ResourceManager.GetString("LoggingStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring web host in {0} Environment.
        /// </summary>
        public static string LoggingStartUpConfiguration {
            get {
                return ResourceManager.GetString("LoggingStartUpConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting web host ({0})....
        /// </summary>
        public static string LoggingStartUpWebHost {
            get {
                return ResourceManager.GetString("LoggingStartUpWebHost", resourceCulture);
            }
        }
    }
}
